version: "3.8"

services:
  albionmonitor:
    build: .
    container_name: albion-monitor
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "export PYTHONPATH=/AlbionMonitor && python main.py"
    volumes:
      - .:/AlbionMonitor
    networks:
      - albionnet

  postgres:
    image: postgres:15
    container_name: albion-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - albion_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - albionnet

  telegram_bot:
    build: .
    container_name: telegram-bot
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "export PYTHONPATH=/AlbionMonitor && python notifications/telegram.py"
    volumes:
      - .:/AlbionMonitor
    networks:
      - albionnet

volumes:
  albion_pgdata:

networks:
  albionnet:
    driver: bridge