version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: albion-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: albiondb
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: albion-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@albion.local
      PGADMIN_DEFAULT_PASSWORD: 1234

volumes:
  pgdata:
