name: Monitor Albion Items

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      MIN_PROFIT_MARGIN: 0.15
      MAX_PROFIT_MARGIN: 10

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v3

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 📦 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Executar monitoramento
        run: python monitor.py
