name: Albion Monitor

on:
  schedule:
    - cron: "0 * * * *" # Executar a cada hora
  workflow_dispatch: # Permite execução manual

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t albion-monitor .

      - name: Executar container
        run: |
          docker run \
            --env TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
            --env TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
            --env ITEM_NAME="T4_BAG,T5_BAG,T6_BAG" \
            --env CITIES="Caerleon,Bridgewatch,Thetford,Martlock,Fortsterling,Lymhurst,Brecilien" \
            albion-monitor
